//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oelkhiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class user1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Salary { get; set; }
        public string Social_Link { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
